{% set name = "dxfgrabber" %}
{% set version = "1.0.0" %}
{% set sha256 = "b8586172fc8a61471d83f8a66b57442061d1690f4c801e03180a9a7128348b7f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - dxfgrabber

about:
  home: https://github.com/mozman/dxfgrabber
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python library to grab information from DXF drawings - all DXF versions supported.
  doc_url: http://dxfgrabber.readthedocs.io/
  dev_url: https://github.com/mozman/dxfgrabber

extra:
  recipe-maintainers:
    - parente
