{% set name = "dxfgrabber" %}
{% set version = "1.0.1" %}
{% set sha256 = "329ddb5fa5a11c0fd4b83b14615686c62924a323ccf4ef2e7bc5771788d220a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - dxfgrabber

about:
  home: https://github.com/mozman/dxfgrabber
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python library to grab information from DXF drawings - all DXF versions supported.
  doc_url: http://dxfgrabber.readthedocs.io/
  dev_url: https://github.com/mozman/dxfgrabber

extra:
  recipe-maintainers:
    - ericdill
    - parente
