travis:
  secure:
    BINSTAR_TOKEN: erjaayN423/xNe7UQgNEjGDqyHCaN4lrLVd/wp2gFJLcakRV9hmkmetjWUWeVw1gUAo8eZ3cgbdfS7LKOvaWrQatcck8qdZCXEYZbCcCUVJmhWPozorMcm8OYmAXln9P90BycZMvsLFqAsZFZtJKUKdgjQpS842BM+enPagrzTU1Q9Ua/Kq3bq6MRm7Btk+rkD0VrCU/PLM3TY5Pr/Ds4jbC1+/TtwkXgymvFBR3RcCbyA82MnSQSoGzISYRjH4bQUi4TuUZQqx9Pc6VY5vcaEjfZl9mdV9EuWQDvnNVs5jrMpyXAQ3rxZJe+Ln/Inzzp6jhzL2zVfOaHsoLBNkjD6xHoFGLoGPl6i9oIfnAwHLlHgO925WsxTLKR3jTUVlAHd5Op3YWoqk25XPedEHv5mUOyfhfQ19D50+EpqEFhC9Op7p56L1XoW3LtEEeNtoNWerBYLMg8AR6fKU8ziTyE+CeO2J3G+VbshjF9bK3koK9EZgNiHqbPbt05rwHmmZjkgLpGmhdsUA/D1w/qw00S+ITk5vGuzDSFHYL8sXD4YfrjEKObof+pKNKK9lI6LBlcvcTAy6wai6hUyHBN7M83t279BJKwMeUb4pVQ/BfIPQSPQZBoTrebp9Irijx3oe8X/D+qAtLPHkqQGUx0sPfpL7GrveFFeWNe7yWOboga6A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
