travis:
  secure:
    BINSTAR_TOKEN: kV61oQHUwAFuVQZspxK+qBIpRxQDQ1KUqAqFyubU5lwsTD7rPPvdPMcFU4rcso6+FFqw7h3FPTahdFco1aumCMJE/InaT5J0yEQg1DLoDjLjBJ4hLGGyCtbYoGAB3voNCy3h0w4DIEWchJF/3h/bN7PWPxpsxiVib9DygPZoCJrz+b1wAnOcnFNtoOE0aP7/MIzkTMxkqrOOJT5a6RvKp+0tA9k7lBUcmJDx6wnIE3eRcZ45yVIQ34clJ8raM01jQukkx80p2eZJmL+8ctq+Zx1LrCzNgLMb24RHVdtcQGLxa2EFa4YxKHbT/xq+H0RLH+zII2YhRoHdei6yZ4qjdccPpkoqpVPGk2sYghd4QWeGIOeiQv3YZOK/w+/TZdXAa/is+W1K1v3+BrkuILFkNtLc9Znk7UwV84WxmUqedMUjBxvlHbRQVdwQOlPJGdLy1oKzC4GgfEHFf4KWN9+r6ot2T6O74kppJnlByG1Zm72MhgfgPacgiBSAl7fjQf45+5bsPJiyiLjTVl2EtRNFfSoBPj49HTbwN49RaZSn8FbBW9lbHUj9Xvm8ZherspvvowdPtDCfNVQOSGR/K2Byfu1UG2Xgh7uTe39HFt1ILRJKREaw3cQvkcDO76gFzRC5I8PvD2dj1Ffk+5ttLQja15F8ZuxOz7dtfDJgQ4hxRic=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
